/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as EarningsRouteImport } from './routes/earnings'
import { Route as KeysRouteImport } from './routes/keys'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiTradingAppV1HealthLiveRouteImport } from './routes/api/trading-app/v1/health/live'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const EarningsRoute = EarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const KeysRoute = KeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTradingAppV1HealthLiveRoute =
  ApiTradingAppV1HealthLiveRouteImport.update({
    id: '/api/trading-app/v1/health/live',
    path: '/api/trading-app/v1/health/live',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/earnings': typeof EarningsRoute
  '/keys': typeof KeysRoute
  '/login': typeof LoginRoute
  '/predictions': typeof PredictionsRoute
  '/results': typeof ResultsRoute
  '/trade': typeof TradeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trading-app/v1/health/live': typeof ApiTradingAppV1HealthLiveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/earnings': typeof EarningsRoute
  '/keys': typeof KeysRoute
  '/login': typeof LoginRoute
  '/predictions': typeof PredictionsRoute
  '/results': typeof ResultsRoute
  '/trade': typeof TradeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trading-app/v1/health/live': typeof ApiTradingAppV1HealthLiveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/earnings': typeof EarningsRoute
  '/keys': typeof KeysRoute
  '/login': typeof LoginRoute
  '/predictions': typeof PredictionsRoute
  '/results': typeof ResultsRoute
  '/trade': typeof TradeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trading-app/v1/health/live': typeof ApiTradingAppV1HealthLiveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/earnings'
    | '/keys'
    | '/login'
    | '/predictions'
    | '/results'
    | '/trade'
    | '/api/auth/$'
    | '/api/trading-app/v1/health/live'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/earnings'
    | '/keys'
    | '/login'
    | '/predictions'
    | '/results'
    | '/trade'
    | '/api/auth/$'
    | '/api/trading-app/v1/health/live'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/earnings'
    | '/keys'
    | '/login'
    | '/predictions'
    | '/results'
    | '/trade'
    | '/api/auth/$'
    | '/api/trading-app/v1/health/live'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  EarningsRoute: typeof EarningsRoute
  KeysRoute: typeof KeysRoute
  LoginRoute: typeof LoginRoute
  PredictionsRoute: typeof PredictionsRoute
  ResultsRoute: typeof ResultsRoute
  TradeRoute: typeof TradeRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTradingAppV1HealthLiveRoute: typeof ApiTradingAppV1HealthLiveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earnings': {
      id: '/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof EarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keys': {
      id: '/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof KeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trading-app/v1/health/live': {
      id: '/api/trading-app/v1/health/live'
      path: '/api/trading-app/v1/health/live'
      fullPath: '/api/trading-app/v1/health/live'
      preLoaderRoute: typeof ApiTradingAppV1HealthLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  EarningsRoute: EarningsRoute,
  KeysRoute: KeysRoute,
  LoginRoute: LoginRoute,
  PredictionsRoute: PredictionsRoute,
  ResultsRoute: ResultsRoute,
  TradeRoute: TradeRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTradingAppV1HealthLiveRoute: ApiTradingAppV1HealthLiveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
